Add mocha tests for app.connect method
jack-lewin/watch-github-labels pull request #2
Opened 2017-10-03 13:58 UTC by jacquesdev

@jack-lewin - have added one test to start off, just to get mocha in place, let me know if you are happy with this, happy to make edits where required..

I was hoping to test whether the github object was actually successfully authenticated or not, but I wasn't sure if there is any property on the object to tell me this, I guess it's something useful to test. I did add this issue to check if something like this was available (and maybe you know). https://github.com/mikedeboer/node-github/issues/597.

If you are happy with this, I will hand it over to Theo to add some more of the actual tests.

2017-10-03 16:27 UTC, jack-lewin requested changes
Looking good! 👌

One thing I should've mentioned - I'm using [StandardJS](https://standardjs.com) as a style guide/linter. Would you mind just making sure we've got a consistent style, please? It comes as a plugin for most editors, there's a pretty good list on the website. Thanks a lot!

2017-10-03 16:27 UTC, jack-lewin commented on app.js
> +  if (process.env.GITHUB_OAUTH !== undefined) {
Could we make this `if (typeof process.env.GITHUB_OAUTH !== 'undefined')`?

[This StackOverflow answer explains it well](https://stackoverflow.com/a/4725697) 👍

2017-10-04 08:52 UTC, jacquesdev commented
Hi @jack-lewin.

I have made the updates as requested, and have added standard.js to the project which means it will run the linter as part of the tests (and should now look ok in your editor).

I have left sinon in there, because ideally I should probably stub the github.authenticate method instead of checking the actual value, but I was having some troubles getting that to work. But will look at updating that after. In the meantime, when this gets merged, Theo can get started.

2017-10-04 09:30 UTC, jack-lewin approved these changes

2017-10-04 09:33 UTC, merged

2017-10-04 09:35 UTC, jack-lewin commented
Awesome, thanks for adding standard to `npm test` as well. Looking good for @tmarkovic to get started.

2017-10-04 10:17 UTC, tmarkovic commented
Hey! 

Nicely done, I'll try to dig in after work. I see no reason for me to monopolize this issue so if you're willing and able, write tests like there's no tomorow and I'll try to contribute where needed 👍

2017-10-04 15:20 UTC, jacquesdev commented
Thanks @tmarkovic - I will try and add a couple of tests nearer the end of the week, so feel free to start where @jack-lewin suggested, basically the module that follows the connect module.